[profile.default]
src = "src"
out = "artifacts"
evm_version = "shanghai"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/contracts=lib/openzeppelin-contracts/contracts/",
    "@prb/math=lib/prb-math/",
]
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
int_types = "long"
tab_width = 2

[rpc_endpoints]
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/aa959c8b01204689b1cceaf56c4d4297"

[etherscan]
arbitrum-goerli = { key = "N89QM8KDR8SZ52I7YCSN6Z35QAUFUYBHBV" }
arbitrum-sepolia = { key = "N89QM8KDR8SZ52I7YCSN6Z35QAUFUYBHBV" }
arbitrum = { key = "N89QM8KDR8SZ52I7YCSN6Z35QAUFUYBHBV" }
sepolia = { key = "MMGCJXPZ3J392VFETA9Y9425IB41A6FWXW" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
